### ISSUE TITLE
autoload/abeans fails to launch org.ensime.server.Server

### ISSUE THREAD

**Issue by megaannum** [jlc/envim#3]
If I place an echoe statement in abeans#start, the ensime server is
started. But without such an additional statement, it is not launched
  sleep 1
  nbstart:127.0.0.1:60101
  echoe "RME: after nbstart"
Have not tried placing the echoe  statement in other places within the abeans
code.

**Comment by jlc** [comment]
Events are triggered in different order between osx and linux.
More specially, the message to start ensime server was sent before input/output buffers have been initialized.

The commit 0bb392c5 should solve it by stacking messages.

However, output of ensime server is still not displayed as it should, this will be fixed soon.

Thanks!!

I take it also as a reminder to do more testing on Linux.
